//"use client";
import type { NextPage } from "next";
import Head from "next/head";
import Carusel from "./c/carusel";
import CaruselMin from "./c/caruselmin";
import CaruselSpec from "./c/caruselspec";
// import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Container, Header, Button } from "@salutejs/plasma-ui";
import Tabbar from "./c/tabbar";
// import Link from "next/link";
// import CaruselCard from "./c/caruselcard.tsx";

import { useEffect, useState } from "react";

// import { useSection } from "@salutejs/spatial";

const Home: NextPage = () => {
  // const [sec1] = useSection("sec1");
  // console.log({ ...sec1 });
  // const [s2] = useSection("s2");
  // const [s3] = useSection("s3");
  // const [s4] = useSection("s4");
  // const [h1, c4] = useSection("h1");
  // useEffect(() => {
  //   c1({
  //     simpleSectionOptions: { type: "row" },

  //   });
  //   // c2({
  //   //   simpleSectionOptions: { type: "row" },
  //   // });
  //   // c3({
  //   //   simpleSectionOptions: { type: "row" },
  //   // });
  //   // c4({
  //   //   simpleSectionOptions: { type: "row" },
  //   // });
  //   // c5({
  //   //   simpleSectionOptions: { type: "row" },
  //   });
  // }, [c1]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next aSApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div>
          <Tabbar />
        </div>
      </Container>
      <Container>
        <div>
          <Carusel />
        </div>
        <div>
          <CaruselSpec />
        </div>
        <div>
          <CaruselMin />
        </div>
        <div>
          <CaruselMin />
        </div>
      </Container>
    </div>
  );
};

export default Home;
